export const NAVIGATION = {
    LOGIN: "LOGIN",

    HOME: "HOME",
    TAB_HOME: "TAB_HOME",
    TAB_USER: "TAB_USER",
    TAB_NOTIFICATION: "TAB_NOTIFICATION",
    TAB_FEEDS: "TAB_FEED",

    DETAIL_PLANT: "DETAIL_PLANT",
    REPORT_FACTORY: "REPORT_FACTORY",
    REPORT_INVERTER: "REPORT_INVERTER",
    REPORT_AC: "REPORT_AC",
    REPORT_DC: "REPORT_DC",
};
