export const NAVIGATION = {
    LOGIN: "LOGIN",

    HOME: "HOME",
    TAB_HOME: "TAB_HOME",
    TAB_USER: "TAB_USER",
    TAB_MANAGEMENT: "TAB_MANAGEMENT",
    TAB_MAINTAIN: "TAB_MAINTAIN",
    TAB_ALARM: "TAB_ALARM",

    DETAIL_PLANT: "DETAIL_PLANT",
    DP_REPORT_FACTORY: "REPORT_FACTORY",
    DP_REPORT_INVERTER: "REPORT_INVERTER",
    DP_REPORT_AC: "REPORT_AC",
    DP_REPORT_DC: "REPORT_DC",
    DP_REPORT_PERFORMANCE: "REPORT_PERFORMANCE",
    DP_REPORT_POTENTIAL_ERROR: "REPORT_POTENTIAL_ERROR",

    REPORT_PLANT_YIELD: "REPORT_PLANT_YIELD",
    REPORT_PLANT_MATERIAL: "REPORT_PLANT_MATERIAL",
    REPORT_PLANT_LOG_REPAIR: "REPORT_PLANT_LOG_REPAIR",
    REPORT_PLANT_POTENTIAL_ERROR: "REPORT_PLANT_POTENTIAL_ERROR",
    REPORT_MAINTENANCE: "REPORT_MAINTENANCE",
    REPORT_PLAN_MAINTENANCE: "REPORT_PLAN_MAINTENANCE",

    DETAIL_DEVICE: "DETAIL_DEVICE",

    ALLE_ERROR: "ALLE_ERROR",
    ERROR_AC: "ERROR_AC",
    INACTIVE_INVERTER: "INACTIVE_INVERTER",
    ERROR_DC: "ERROR_DC",
    PERFORMANCE: "PERFOMANCE",
    POTENTIAL_ERROR: "POTENTIAL_ERROR",
    ERROR_RESISTOR: "ERROR_RESISTOR",
    ERROR_DISCONNECT: "ERROR_DISCONNECT",
    RS_UPDATION: "RS_UPDATION",
    RS_UPDATE_MULTIPLE: "RS_UPDATE_MULTIPLE",
    ERROR_POTENTIEL_CREATION: "ERROR_POTENTIEL_CREATION",

    ALARM: "ALARM",

    MATERIAL: "MATERIAL",

    MAINTAINANCE_LIST_WORK: "MAINTAINANCE_LIST_WORK",
    MAINTAINANCE_CATEGORY: "MAINTAINANCE_CATEGORY",
};
