export const NAVIGATION = {
    LOGIN: "LOGIN",

    HOME: "HOME",
    TAB_HOME: "TAB_HOME",
    TAB_USER: "TAB_USER",
    TAB_MANAGEMENT: "TAB_MANAGEMENT",
    TAB_MAINTAIN: "TAB_MAINTAIN",

    DETAIL_PLANT: "DETAIL_PLANT",
    REPORT_FACTORY: "REPORT_FACTORY",
    REPORT_INVERTER: "REPORT_INVERTER",
    REPORT_AC: "REPORT_AC",
    REPORT_DC: "REPORT_DC",

    REPORT_PLANT_YIELD: "REPORT_PLANT_YIELD",
    REPORT_PLANT_MATERIAL: "REPORT_PLANT_MATERIAL",
    REPORT_PLANT_LOG_REPAIR: "REPORT_PLANT_LOG_REPAIR",
    REPORT_PLANT_POTENTIAL_ERROR: "REPORT_PLANT_POTENTIAL_ERROR",
    REPORT_MAINTENANCE: "REPORT_MAINTENANCE",

    ERROR_AC: "ERROR_AC",
    ERROR_DC: "ERROR_DC",
    PERFORMANCE: "PERFOMANCE",
    POTENTIAL_ERROR: "POTENTIAL_ERROR",
};
